// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpQu92OpDNe0BgzsXQQEd1AN5NJq-DYs',
    appId: '1:513756598379:web:0f7db2e5ee82e6c9d9612e',
    messagingSenderId: '513756598379',
    projectId: 'walkmoment-36261',
    authDomain: 'walkmoment-36261.firebaseapp.com',
    storageBucket: 'walkmoment-36261.appspot.com',
    measurementId: 'G-YYQEWFQ0B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPiyjtjF6esq1Y3I789r3616sT7LrJ0I',
    appId: '1:513756598379:android:20c46ed52992bbe0d9612e',
    messagingSenderId: '513756598379',
    projectId: 'walkmoment-36261',
    storageBucket: 'walkmoment-36261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnS3tj9UTDJTrp0kc_gFUJpTEHF2B4Hj8',
    appId: '1:513756598379:ios:86aabec940385dedd9612e',
    messagingSenderId: '513756598379',
    projectId: 'walkmoment-36261',
    storageBucket: 'walkmoment-36261.appspot.com',
    iosClientId: '513756598379-j8pp0h2lp1k9p0ocoe55f5s68df1qbh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkmoment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnS3tj9UTDJTrp0kc_gFUJpTEHF2B4Hj8',
    appId: '1:513756598379:ios:c39094a0e982066dd9612e',
    messagingSenderId: '513756598379',
    projectId: 'walkmoment-36261',
    storageBucket: 'walkmoment-36261.appspot.com',
    iosClientId: '513756598379-894i84730kub5tesgmugb6cj0tfn6164.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkmoment.RunnerTests',
  );
}
